language: c

sudo: true

os: linux
dist: xenial
sudo: required

services: docker

notifications:
  email: false

install:
  - docker pull devkitpro/devkitarm

script:
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/LimePlayer3DS devkitpro/devkitarm /bin/bash -ex /LimePlayer3DS/.travis/build.sh
